Models/Customer.cs
using System.ComponentModel.DataAnnotations;

namespace Banking_System.Models
{
    public class Customer
    {
        [Key]
        public int Id { get; set; }
        [Required]
        public string? Name { get; set; }
        public string? UserImageUrl { get; set; }

        [DataType(DataType.EmailAddress)]
        public string? Email { get; set; }
        public string? PhoneNumber { get; set; }
        public int? Balance { get; set; }

    }
}

Models/ErrorViewModel.cs
namespace Banking_System.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Transfer.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
namespace Banking_System.Models
{
    public class Transfer
    {
        [Key]
        public int Id { get; set; }
        public int FromId { get; set; }
        public int ToId { get; set; }
        public int AmountOfMoney { get; set; }
        public DateTime? Date { get; set; }

        [ForeignKey("FromId")]
        public virtual Customer? customerFrom { get; set; }

        [ForeignKey("ToId")]
        public virtual Customer? customerTo { get; set; }

    }
}

Controllers/HomeController.cs
using Banking_System.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Banking_System.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private ApplicationDbContext db;

        public HomeController(ILogger<HomeController> logger, ApplicationDbContext db)
        {
            _logger = logger;
            this.db = db;
        }

        public IActionResult Index()
        {
            IEnumerable<Customer> customers = db.Customers.ToList();
            return View(customers);
        }
        public IActionResult Profile(int id)
        {
            Customer customer = db.Customers.Find(id);
            return View(customer);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/TransferController.cs
using Banking_System.Models;
using Banking_System.ViewModel;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace Banking_System.Controllers
{
    public class TransferController : Controller
    {
        private ApplicationDbContext db;
        public TransferController(ApplicationDbContext db)
        {
            this.db = db;
        }
        [HttpGet]
        public IActionResult AddTransfer(int id)
        {
            AddTransferVM trans = new AddTransferVM();
            trans.customerFrom = db.Customers.Find(id);
            trans.customers = db.Customers.Select(n => new SelectListItem { Value = n.Id.ToString(), Text = n.Name }).ToList();
            return View(trans);
        }
        [HttpPost]
        public IActionResult AddTransfer(int from, int to,int money)
        {
            Transfer tra = new Transfer();
            tra.AmountOfMoney = money;
            tra.Date = DateTime.Now;
            tra.FromId = from;
            tra.ToId = to;
            db.Transfers.Add(tra);
            db.SaveChanges();

            Customer cus1 = db.Customers.Find(from);
            cus1.Balance -= money;
            db.Entry(cus1).State = Microsoft.EntityFrameworkCore.EntityState.Modified;
            db.SaveChanges();

            Customer cus2 = db.Customers.Find(to);
            cus2.Balance += money;
            db.Entry(cus2).State = Microsoft.EntityFrameworkCore.EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("Index","Home");
        }

        public IActionResult DisplayTransfer()
        {
            IEnumerable<Transfer> transfer = db.Transfers.Include(e => e.customerFrom).Include(e =>e.customerTo).ToList();
            return View(transfer);
        }
    }
}

Views/Home/Index.cshtml
@model IEnumerable<Banking_System.Models.Customer>
@{
    ViewData["Title"] = "Home Page";
}


<link rel="stylesheet" href="~/css/HomeStyle.css" asp-append-version="true" />

<div class="slide ">

<div id="main-slider" class="carousel slide w-100" data-bs-ride="carousel">
    <ol class="carousel-indicators">
            <li  data-bs-target="#main-slider" data-bs-slide-to="0" class="active"></li>
            <li  data-bs-target="#main-slider" data-bs-slide-to="1" ></li>
            <li  data-bs-target="#main-slider" data-bs-slide-to="2" ></li>
    </ol>

  <div class="carousel-inner">
            <h1>Welcome In  <span> Banking System </span><br /></h1>
            <div class="overlay"> </div>
                   <div class="carousel-item active" style="background-image: url('../Images/bank1.jpg');"></div>
                   <div class="carousel-item " style="background-image: url('../Images/bank2.jpg');"></div>
                   <div class="carousel-item " style="background-image: url('../Images/bank3.jpg');"></div>
  </div>
     
  <button class="carousel-control-prev" type="button" data-bs-target="#main-slider" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#main-slider" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>

</div>
@*-----------------------------------------------------------------------------------------------------------------------*@
<br /><br /><br />

<h1>All Customers</h1>


<table class="table">
    <thead>
        <tr>
            <th>
               Number
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PhoneNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Balance)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PhoneNumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Balance)$
            </td>
            <td>
                <a href="/Transfer/AddTransfer/@item.Id">Transfer </a> |
                <a asp-action="Profile" asp-route-id="@item.Id">Details</a>             
            </td>
        </tr>
}
    </tbody>
</table>

Views/Home/Profile.cshtml
@model Banking_System.Models.Customer
@{
    ViewData["Title"] = "Add Transfer";
}

<section class="vh-100" style="background-color: gray;">
  <div class="container py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-md-12 col-xl-4">

        <div class="card" style="border-radius: 15px;">
          <div class="card-body text-center">
            <div class="mt-3 mb-4">
              <img src="@Model.UserImageUrl"
                class="rounded-circle img-fluid" style="width: 100px;" />
            </div>
            <h4 class="mb-2">@Model.Name</h4>
            <p class="text-muted mb-4">@Model.PhoneNumber <span class="mx-2">|</span> <a
                href="#!">@Model.Email</a></p>

            <h4>Balance : @Model.Balance$</h4>
            
          </div>
        </div>

      </div>
    </div>
  </div>
</section>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Banking_System</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Banking_System.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Banking_System</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Transfer" asp-action="DisplayTransfer">Transfer Table</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Banking_System - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Transfer/AddTransfer.cshtml
@model Banking_System.ViewModel.AddTransferVM
@{
    ViewData["Title"] = "Add Transfer";
}


<div class="container">
        <div class="row mt-2">
            <div class="col-lg-3 col-md-2"></div>
            <div class="col-lg-6 col-md-8 " style="background-color:#D3D3D3;">
                <div class="col-lg-12 text-center ">
                    <img src="~/Images/transfer.png" alt="no image" style="width: 100px; height: 100px;" />
                </div>
                <h3 class="col-lg-12 text-center text-dark">
                   @Model.customerFrom.Name
                </h3>


                <div class="col-lg-12 login-form">
                    <div class="col-lg-12 login-form">
                        <form method="post" asp-action="AddTransfer" enctype="multipart/form-data">
                          <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            
               <!-- From  List of Customer -->
                    <div class="form-group">
                           <input name="from" value ="@Model.customerFrom.Id" asp-for="@Model.customerFrom.Id" class="form-control" type="hidden" required/>
                    </div>

               <!-- To  List of Customer-->
                      <div class="form-group">
                          <label asp-for="@Model.transfer.ToId" class="control-label text-dark">To</label>
                          <select name="to" asp-items="@Model.customers" class="form-select" required>
                             <option value="">Choose</option>
                          </select>
                      </div>

               <!-- Amount of money-->
                            <div class="form-group">
                               <label asp-for="transfer.AmountOfMoney" class="control-label text-dark"> Amount Of Money </label>
                               <input name="money" asp-for="transfer.AmountOfMoney" class="form-control" type="number" required/>
                               <span asp-validation-for="transfer.AmountOfMoney" class="text-danger"></span>
                            </div>



                     <!-- Bottom  -->
                           <div class="col-lg-12 mt-2 mb-2">
                                <div class="col-lg-6 ">
                                     
                                    <!-- Error Message  -->
                                </div>
                                <div class="col-lg-6 ">
                                    <input type="submit" value="اضافه"  class="btn btn-outline-dark" />
                                </div>
                            </div>
                     </form>
                    
                    </div>
                </div>
                <div class="col-lg-3 col-md-2"></div>
            </div>
        </div>
    </div>

Views/Transfer/DisplayTransfer.cshtml
@model IEnumerable<Banking_System.Models.Transfer>
@{
    ViewData["Title"] = "Transfer Table";
}

<h2>Transfer Table</h2>

<table>
  <tr>
    <th>Number</th>
    <th>From</th>
    <th>To</th>
    <th>Amount Of Money</th>
    <th>Date</th>
  </tr>
  @foreach(var item in Model)
  {
     <tr>
       <td>@item.Id</td>
       <td>@item.customerFrom.Name</td>
       <td>@item.customerTo.Name</td>
       <td>@item.AmountOfMoney</td>
       <td>@item.Date</td>
     </tr>
  }
</table>



<style>
table {
  font-family: arial, sans-serif;
  border-collapse: collapse;
  width: 100%;
}

td, th {
  border: 1px solid lightgray;
  text-align: left;
  padding: 8px;
}

tr:nth-child(even) {
  background-color: lightgray;
}
</style>